#create ConfigMap with key and value, which has to be accessed by mysql and  while deploying SpringBoot application
#Define a key value for mysql database, a key value for mysql url used by SpringBoot for connecting to mysql
apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-config
data:
#  eureka_url: "http://192.168.99.100:31000/eureka/"
  eureka_url: "http://localhost:8761/eureka/"

