#Create a deployment by using the image pushed to Docker Hub
#containerPort has to be 8761

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbservicetwo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      k8.stackroute: sbservicetwo-deployment
  template:
    metadata:
      labels:
        k8.stackroute: sbservicetwo-deployment
    spec:
      containers:
        - name: sbservicet-swoervice
          image: jaswanth1234/sbservicetwo:1.0
          env:
            - name: EUREKA_URL
              valueFrom:
                configMapKeyRef:
                  name: eureka-config
                  key: eureka_url
          ports:
            - containerPort: 8082
---
#Create the service of type LoadBalancer and use the above created deployment as selector
#port should be 8082

apiVersion: v1
kind: Service
metadata:
  name: sbservicetwo-service
  labels:
    app: sbservicetwo-service
spec:
  type: NodePort
  ports:
    - nodePort: 31003
      port: 8082
      targetPort: 8082
  selector:
    k8.stackroute: sbservicetwo-deployment

